import { useMemo, useState } from 'react';
import { AdminBadge, AdminDrawer, AdminHeader, AdminIcon, AdminPanel, AdminSearch, AdminSelect, AdminStat } from '../components/AdminUI';
import { adminAuditEvents } from '../data/adminData';

export function AuditTrailPage() {
  const [query, setQuery] = useState('');
  const [depot, setDepot] = useState('All depots');
  const [status, setStatus] = useState('All statuses');
  const [selected, setSelected] = useState<(typeof adminAuditEvents)[number] | null>(null);
  const rows = useMemo(() => adminAuditEvents.filter((event) => (!query || `${event.id} ${event.event} ${event.person} ${event.ref}`.toLowerCase().includes(query.toLowerCase())) && (depot === 'All depots' || event.depot === depot) && (status === 'All statuses' || event.status === status)), [query, depot, status]);
  return <div className="admin-page"><AdminHeader title="Audit Trail" subtitle="Every decision, change, and confirmation in one place." action={<button className="admin-button secondary" type="button" onClick={() => window.print()}><AdminIcon name="download"/>Export report</button>}/>
    <div className="admin-toolbar"><div className="admin-toolbar-filters"><AdminSelect value={depot} values={['All depots','Peliyagoda','Kandy']} onChange={setDepot}/><AdminSelect value={status} values={['All statuses','Recorded','Conflict']} onChange={setStatus}/></div><AdminBadge tone="neutral">Sample workspace</AdminBadge></div>
    <div className="admin-stats-grid four"><AdminStat label="Recorded events" value="6" note="Events in the sample workspace" icon={<AdminIcon name="file"/>}/><AdminStat label="Offline events" value="01" note="Original event time preserved" icon={<AdminIcon name="sync"/>}/><AdminStat label="Open conflicts" value="01" note="Requires operational review" icon={<AdminIcon name="alert"/>} tone="amber"/><AdminStat label="Admin changes" value="01" note="All changes have an audit record" icon={<AdminIcon name="shield"/>}/></div>
    <AdminPanel title="Activity log" action={<AdminSearch value={query} onChange={setQuery}/> } className="admin-data-panel"><div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>Event / record</th><th>Person</th><th>Depot</th><th>Event time</th><th>Received</th><th>Status</th><th/></tr></thead><tbody>{rows.map((event) => <tr key={event.id} onClick={() => setSelected(event)}><td><strong>{event.event}</strong><small>{event.ref}</small></td><td><strong>{event.person}</strong><small>{event.role}</small></td><td><b>{event.depot}</b></td><td><b>{event.eventTime}</b></td><td>{event.received}</td><td><AdminBadge tone={event.status === 'Conflict' ? 'red' : 'green'}>{event.status}</AdminBadge></td><td><button type="button" className="admin-text-link" onClick={(e) => { e.stopPropagation(); setSelected(event); }}>Details <AdminIcon name="chevron"/></button></td></tr>)}</tbody></table></div><footer className="admin-table-footer"><span>{rows.length} events</span><span>Corrections create new events. History is retained.</span></footer></AdminPanel>
    {selected && <AdminDrawer title={selected.id} subtitle="Permanent event history" onClose={() => setSelected(null)}><AdminBadge tone={selected.status === 'Conflict' ? 'red' : 'green'}>{selected.status}</AdminBadge><h3 className="admin-drawer-event-title">{selected.event}</h3><dl className="admin-detail-grid"><div><dt>Actor</dt><dd>{selected.person}</dd></div><div><dt>Role</dt><dd>{selected.role}</dd></div><div><dt>Record</dt><dd>{selected.ref.split(' · ')[0]}</dd></div><div><dt>Depot</dt><dd>{selected.depot}</dd></div><div><dt>Event time</dt><dd>{selected.eventTime}</dd></div><div><dt>Received by server</dt><dd>{selected.received}</dd></div></dl><AdminPanel title="Change recorded"><p className="admin-drawer-note">This event is preserved in the permanent audit history.</p></AdminPanel></AdminDrawer>}
  </div>;
}
