import { useState } from 'react';
import { AdminHeader, AdminIcon, AdminPanel } from '../components/AdminUI';

export function ConfigurationPage(){
  const [cutoff,setCutoff]=useState('16:00');const [repeatedDeferrals,setRepeatedDeferrals]=useState(true);const [offlineHistory,setOfflineHistory]=useState(true);const [arrivalAlerts,setArrivalAlerts]=useState(true);const [loadingAlerts,setLoadingAlerts]=useState(true);const [saved,setSaved]=useState(false);
  const Toggle=({checked,onChange,label}:{checked:boolean;onChange:()=>void;label:string})=><button type="button" className={`admin-switch${checked?' on':''}`} onClick={onChange} role="switch" aria-checked={checked} aria-label={label}><i/></button>;
  const Required=()=> <span className="admin-required">✓ Required</span>;
  return <div className="admin-page admin-config-page"><AdminHeader title="Configuration" subtitle="Manage the rules that keep your operations consistent." action={<button className="admin-button primary" type="button" onClick={()=>{setSaved(true);setTimeout(()=>setSaved(false),2600)}}><AdminIcon name="check"/>Save changes</button>}/>
    <div className="admin-config-grid"><AdminPanel title="Operational rules" icon={<AdminIcon name="sync"/>} className="admin-config-explainer"><p>These settings apply across both depots. Individual vehicle limits and outlet windows are managed in Master Data.</p><div className="admin-config-note"><AdminIcon name="shield"/><strong>Every saved change includes a reason and appears in the Audit Trail.</strong></div><small>Last saved: 28 Sep 2026, 04:10 PM<br/>By Dilini Rathnayake</small></AdminPanel>
      <div className="admin-config-sections"><AdminPanel title="Ordering & planning" icon={<AdminIcon name="box"/>}><div className="admin-setting-row"><div><strong>Next-day order cutoff</strong><small>Late orders move to the following eligible run.</small></div><label className="admin-setting-control"><select value={cutoff} onChange={(e)=>setCutoff(e.target.value)}><option>16:00</option><option>15:00</option><option>17:00</option></select><AdminIcon name="down"/></label></div><div className="admin-setting-row"><div><strong>Maximum routes per vehicle</strong><small>Daily route limit from the challenge brief.</small></div><AdminPill>2 routes / day</AdminPill></div><div className="admin-setting-row"><div><strong>Fresh delivery deadline</strong><small>Individual outlet windows may close earlier.</small></div><AdminPill tone="amber">Before 8:00 AM</AdminPill></div><div className="admin-setting-row"><div><strong>Constraint validation</strong><small>Weight, volume, temperature, van access, windows, and fuel.</small></div><Required/></div></AdminPanel>
        <AdminPanel title="Deferrals & record integrity" icon={<AdminIcon name="shield"/>}><div className="admin-setting-row"><div><strong>Require a deferral reason</strong><small>A reason is recorded before an order is deferred.</small></div><Required/></div><div className="admin-setting-row"><div><strong>Warn on repeated deferrals</strong><small>Highlight outlets skipped on consecutive operating runs.</small></div><Toggle checked={repeatedDeferrals} onChange={()=>setRepeatedDeferrals((x)=>!x)} label="Warn on repeated deferrals"/></div><div className="admin-setting-row"><div><strong>Preserve offline event history</strong><small>Keep device event time, sync time, and conflicting changes.</small></div><Required/></div></AdminPanel>
        <AdminPanel title="Notifications" icon={<AdminIcon name="clock"/>}><div className="admin-setting-row"><div><strong>Revised arrival alerts</strong><small>Notify store managers when a delivery ETA changes.</small></div><Toggle checked={arrivalAlerts} onChange={()=>setArrivalAlerts((x)=>!x)} label="Revised arrival alerts"/></div><div className="admin-setting-row"><div><strong>Loading plan changes</strong><small>Notify loaders when assignments change after loading starts.</small></div><Toggle checked={loadingAlerts} onChange={()=>setLoadingAlerts((x)=>!x)} label="Loading plan changes"/></div></AdminPanel></div>
    </div>{saved&&<div className="admin-toast" role="status">Configuration changes saved<button onClick={()=>setSaved(false)} type="button">×</button></div>}
  </div>;
}

function AdminPill({children,tone='purple'}:{children:string;tone?:'purple'|'amber'}){return <span className={`admin-pill ${tone}`}>{children}</span>}
