import { useMemo, useState } from 'react';
import { AdminBadge, AdminDrawer, AdminHeader, AdminIcon, AdminPanel, AdminSearch, AdminSelect, AdminStat } from '../components/AdminUI';
import { adminFineReports } from '../data/adminData';

export function FineLedgerPage() {
  const [query, setQuery] = useState('');
  const [depot, setDepot] = useState('All depots');
  const [status, setStatus] = useState('All statuses');
  const [selected, setSelected] = useState<(typeof adminFineReports)[number] | null>(null);
  const [paid, setPaid] = useState<string[]>([]);
  const rows = useMemo(() => adminFineReports.filter((r) => (!query || `${r.id} ${r.driver} ${r.outlet}`.toLowerCase().includes(query.toLowerCase())) && (depot === 'All depots' || r.depot === depot) && (status === 'All statuses' || r.status === status)), [query,depot,status]);
  return <div className="admin-page"><AdminHeader title="Fine Ledger" subtitle="Follow delivery fines from report to reimbursement." action={<button className="admin-button secondary" type="button" onClick={() => window.print()}><AdminIcon name="download"/>Export report</button>}/><div className="admin-toolbar"><div className="admin-toolbar-filters"><AdminSelect value={depot} values={['All depots','Kandy','Peliyagoda']} onChange={setDepot}/><AdminSelect value={status} values={['All statuses','Reported','Under review','Approved','Paid','Rejected']} onChange={setStatus}/></div><AdminBadge tone="neutral">Sample workspace</AdminBadge></div>
    <div className="admin-stats-grid four"><AdminStat label="Reported & in review" value="02" note="Awaiting Dispatcher decision" icon={<AdminIcon name="file"/>}/><AdminStat label="Approved, unpaid" value="LKR 2,500" note="Company reimbursement due" icon={<AdminIcon name="file"/>}/><AdminStat label="Reimbursed" value="LKR 2,500" note="Paid cases in the sample ledger" icon={<AdminIcon name="check"/>}/><AdminStat label="Rejected reports" value="01" note="Decision and reason recorded" icon={<AdminIcon name="alert"/>} tone="red"/></div>
    <div className="admin-two-panels"><AdminPanel title="Fine status breakdown" icon={<AdminIcon name="file"/>}><div className="admin-simple-chart">{[['Reported',4],['Under review',2],['Approved',1],['Paid',1],['Rejected',1]].map(([name,count])=><div key={name as string}><span>{count}</span><i style={{height:`${Number(count)*20}%`}}/><small>{name}</small></div>)}</div></AdminPanel><AdminPanel title="Repeated fine locations" icon={<AdminIcon name="pin"/>}><div className="admin-repeat-row"><strong>Fresh · Katugastota</strong><AdminBadge tone="amber">3 reports</AdminBadge><i/><small>Last 30 days · Curbside unloading</small></div><div className="admin-repeat-row"><strong>Style · Colombo 03</strong><span>2 reports</span><i/><small>Last 30 days · Mall loading bay</small></div><button className="admin-text-link" type="button">Review outlet access <AdminIcon name="chevron"/></button></AdminPanel></div>
    <AdminPanel title="Fine reports" action={<AdminSearch value={query} onChange={setQuery}/>} className="admin-data-panel"><div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>Report / driver</th><th>Outlet</th><th>Depot</th><th>Date</th><th>Amount</th><th>Status</th><th/></tr></thead><tbody>{rows.map((r)=>{const rowStatus=paid.includes(r.id)?'Paid':r.status;return <tr key={r.id} onClick={()=>setSelected(r)}><td><strong>{r.id}</strong><small>{r.driver} · {r.vehicle}</small></td><td><b>{r.outlet}</b></td><td>{r.depot}</td><td>{r.date}</td><td><b>{r.amount}</b></td><td><AdminBadge tone={rowStatus==='Approved'?'blue':rowStatus==='Paid'?'green':rowStatus==='Rejected'?'red':'amber'}>{rowStatus}</AdminBadge></td><td><button type="button" className="admin-text-link" onClick={(e)=>{e.stopPropagation();setSelected(r)}}>View <AdminIcon name="chevron"/></button></td></tr>})}</tbody></table></div><footer className="admin-table-footer">{rows.length} reports</footer></AdminPanel>
    {selected&&<AdminDrawer title={selected.id} subtitle="Fine report and reimbursement history" onClose={()=>setSelected(null)}><AdminBadge tone={paid.includes(selected.id)?'green':selected.status==='Approved'?'blue':'amber'}>{paid.includes(selected.id)?'Paid':selected.status}</AdminBadge><h3 className="admin-drawer-amount">{selected.amount}</h3><dl className="admin-detail-grid"><div><dt>Driver</dt><dd>{selected.driver}</dd></div><div><dt>Vehicle</dt><dd>{selected.vehicle}</dd></div><div><dt>Outlet</dt><dd>{selected.outlet}</dd></div><div><dt>Depot</dt><dd>{selected.depot}</dd></div><div><dt>Date</dt><dd>{selected.date}</dd></div><div><dt>Event time</dt><dd>06:45 AM</dd></div></dl><section className="admin-drawer-section"><h3>Driver’s report</h3><p className="admin-drawer-note">{selected.reason}</p></section><section className="admin-drawer-section"><h3>Ticket evidence</h3><div className="admin-drawer-note">▤<br/>No ticket image is included in this sample record.</div></section>{selected.status==='Approved'&&!paid.includes(selected.id)&&<button className="admin-button primary full" onClick={()=>setPaid((current)=>[...current,selected.id])} type="button">Record reimbursement</button>}</AdminDrawer>}
  </div>;
}
