import { useMemo, useState } from 'react';
import { AdminBadge, AdminDrawer, AdminHeader, AdminIcon, AdminPanel, AdminSearch, AdminSelect, AdminStat } from '../components/AdminUI';
import { adminUsers } from '../data/adminData';

type UserRow = typeof adminUsers[number];
export function UsersPage() {
  const [users,setUsers]=useState<UserRow[]>(adminUsers);const [query,setQuery]=useState('');const [depot,setDepot]=useState('All depots');const [status,setStatus]=useState('All statuses');const [selected,setSelected]=useState<UserRow|null>(null);const [creating,setCreating]=useState(false);const [newName,setNewName]=useState('');const [newEmail,setNewEmail]=useState('');const [newRole,setNewRole]=useState('Dispatcher');const [notice,setNotice]=useState('');
  const rows=useMemo(()=>users.filter(u=>(!query||`${u.name} ${u.email} ${u.role}`.toLowerCase().includes(query.toLowerCase()))&&(depot==='All depots'||u.access===depot||u.access==='All depots')&&(status==='All statuses'||u.status===status)),[users,query,depot,status]);
  const saveUser=()=>{if(!newName.trim()||!newEmail.trim())return;const initials=newName.trim().split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();setUsers((current)=>[{name:newName.trim(),email:newEmail.trim(),role:newRole,access:'All depots',lastActivity:'Never',status:'Active',initials},...current]);setCreating(false);setNewName('');setNewEmail('');setNotice('User added to the sample workspace.');};
  const toggleUser=(user:UserRow)=>{const updated={...user,status:user.status==='Active'?'Inactive':'Active'};setUsers((current)=>current.map((entry)=>entry.email===user.email?updated:entry));setSelected(updated);};
  return <div className="admin-page"><AdminHeader title="Users" subtitle="Manage people and their access to Waypoint." action={<button className="admin-button primary" onClick={()=>setCreating(true)} type="button"><span>＋</span>Add user</button>}/><div className="admin-toolbar"><div className="admin-toolbar-filters"><AdminSelect value={depot} values={['All depots','Peliyagoda','Kandy']} onChange={setDepot}/><AdminSelect value={status} values={['All statuses','Active','Inactive']} onChange={setStatus}/></div><AdminBadge tone="neutral">Sample workspace</AdminBadge></div>
    <div className="admin-stats-grid four"><AdminStat label="Workspace users" value={String(users.length).padStart(2,'0')} note="Accounts in this prototype" icon={<AdminIcon name="users"/>}/><AdminStat label="Active accounts" value={String(users.filter((u)=>u.status==='Active').length).padStart(2,'0')} note="Can access assigned work" icon={<AdminIcon name="check"/>} tone="green"/><AdminStat label="User roles" value="05" note="Role-based access" icon={<AdminIcon name="shield"/>}/><AdminStat label="Inactive accounts" value={String(users.filter((u)=>u.status==='Inactive').length).padStart(2,'0')} note="Access disabled; history retained" icon={<AdminIcon name="users"/>} tone="amber"/></div>
    <AdminPanel title="People & access" action={<AdminSearch value={query} onChange={setQuery}/>} className="admin-data-panel"><div className="admin-table-scroll"><table className="admin-table admin-users-table"><thead><tr><th>Name</th><th>Role</th><th>Assigned access</th><th>Last activity</th><th>Status</th><th/></tr></thead><tbody>{rows.map((u)=><tr key={u.email}><td><div className="admin-user-cell"><i>{u.initials}</i><span><strong>{u.name}</strong><small>{u.email}</small></span></div></td><td><AdminBadge tone={u.role==='Admin'?'purple':'neutral'}>{u.role}</AdminBadge></td><td><b>{u.access}</b></td><td>{u.lastActivity}</td><td><AdminBadge tone={u.status==='Active'?'green':'neutral'}>{u.status}</AdminBadge></td><td><button type="button" className="admin-text-link" onClick={()=>setSelected(u)}>Manage <AdminIcon name="chevron"/></button></td></tr>)}</tbody></table></div><footer className="admin-table-footer">{rows.length} accounts <span>Account changes are recorded in the audit trail.</span></footer></AdminPanel>
    {creating&&<AdminDrawer title="Add user" subtitle="Create a workspace account" onClose={()=>setCreating(false)}><div className="admin-form"><label>Full name<input value={newName} onChange={(e)=>setNewName(e.target.value)} placeholder="Name"/></label><label>Email address<input type="email" value={newEmail} onChange={(e)=>setNewEmail(e.target.value)} placeholder="name@waypoint.example"/></label><label>Role<select value={newRole} onChange={(e)=>setNewRole(e.target.value)}>{['Dispatcher','Loader','Driver','Store Manager','Admin'].map(r=><option key={r}>{r}</option>)}</select></label><label>Assigned depot<select><option>All depots</option><option>Peliyagoda</option><option>Kandy</option></select></label><button className="admin-button primary full" type="button" onClick={saveUser}>Create user</button></div></AdminDrawer>}
    {selected&&!creating&&<AdminDrawer title={selected.name} subtitle={selected.email} onClose={()=>setSelected(null)}><AdminBadge tone={selected.status==='Active'?'green':'neutral'}>{selected.status}</AdminBadge><dl className="admin-detail-grid"><div><dt>Role</dt><dd>{selected.role}</dd></div><div><dt>Assigned access</dt><dd>{selected.access}</dd></div><div><dt>Last activity</dt><dd>{selected.lastActivity}</dd></div><div><dt>Account</dt><dd>{selected.email}</dd></div></dl><section className="admin-drawer-section"><h3>Access status</h3><p className="admin-drawer-note">Changing access is recorded in the audit trail. Existing event history is retained.</p></section><button className={`admin-button ${selected.status==='Active'?'danger':'primary'} full`} type="button" onClick={()=>toggleUser(selected)}>{selected.status==='Active'?'Deactivate account':'Reactivate account'}</button></AdminDrawer>}
    {notice&&<div className="admin-toast" role="status">{notice}<button onClick={()=>setNotice('')} type="button">×</button></div>}
  </div>;
}
