import { useMemo, useState } from 'react';
import { useOutletContext } from '@/lib/router-compat';
import { DispatchIcon, DispatcherBadge, DispatcherStat } from '../components/DispatcherUI';
import { dispatchHistory } from '../data/dispatcherData';

export function DispatcherHistoryPage() {
  const { searchQuery = '' } = useOutletContext<{ searchQuery?: string }>();
  const [search, setSearch] = useState('');
  const [status, setStatus] = useState('All statuses');
  const [type, setType] = useState('All types');
  const [range, setRange] = useState('Sep 23 – Sep 29');
  const [page, setPage] = useState(1);
  const [detail, setDetail] = useState('');
  const query = `${searchQuery} ${search}`.trim().toLowerCase();
  const events = useMemo(() => dispatchHistory.filter((event) => (!query || `${event.time} ${event.date} ${event.type} ${event.event} ${event.detail} ${event.vehicle} ${event.route} ${event.outcome}`.toLowerCase().includes(query)) && (type === 'All types' || event.type === type.toLowerCase()) && (status === 'All statuses' || event.outcome.toLowerCase().includes(status.toLowerCase()))), [query, type, status]);
  return <div className="dispatch-page dispatch-history-page"><section className="dispatch-history-stats"><DispatcherStat label="Events today" value="48" note="across 29 trips" icon={<DispatchIcon name="check" />} /><DispatcherStat label="Trips completed" value="29" note="94% on time" icon={<DispatchIcon name="pin" />} /><DispatcherStat label="Interventions" value="7" note="avg. 14 min" icon={<DispatchIcon name="alert" />} /><DispatcherStat label="Incidents resolved" value="5" note="0 outstanding" icon={<DispatchIcon name="check" />} /></section>
    {detail && <div className="dispatch-success-notice" role="status">{detail}<button type="button" onClick={() => setDetail('')} aria-label="Dismiss">×</button></div>}
    <div className="dispatch-history-controls"><label className="dispatch-history-search"><span>⌕</span><input type="search" placeholder="Search event, driver, vehicle, route, or ID" value={search} onChange={(event) => setSearch(event.target.value)} /></label><label className="dispatch-date-range"><input aria-label="Date range" value={range} onChange={(event) => setRange(event.target.value)} /><span>▦</span></label><select aria-label="Filter status" value={status} onChange={(event) => setStatus(event.target.value)}>{['All statuses', 'Completed', 'Resolved', 'Support completed'].map((option) => <option key={option}>{option}</option>)}</select><select aria-label="Filter event type" value={type} onChange={(event) => setType(event.target.value)}>{['All types', 'Delivery', 'Incident', 'Intervention', 'Trip'].map((option) => <option key={option}>{option}</option>)}</select></div>
    <section className="dispatch-history-table-card"><div className="dispatch-table-scroll"><table className="dispatch-history-table"><thead><tr><th>Time</th><th>Type</th><th>Event</th><th>Driver / vehicle</th><th>Outcome / owner</th><th></th></tr></thead><tbody>{events.slice((page - 1) * 7, page * 7).map((event) => <tr key={`${event.time}-${event.event}`}><td><strong>{event.time}</strong><small>{event.date}</small></td><td><DispatcherBadge tone={event.type}>{event.type}</DispatcherBadge></td><td><strong>{event.event}</strong><small>{event.detail}</small></td><td><strong>{event.vehicle}</strong><small>{event.route}</small></td><td><strong className={event.type === 'delivery' ? 'dispatch-good-text' : ''}>{event.outcome}</strong><small>{event.owner}</small></td><td><button className="dispatch-text-button" type="button" onClick={() => setDetail(`${event.time} · ${event.event} · ${event.detail}`)}>↗ Details</button></td></tr>)}</tbody></table>{events.length === 0 && <p className="dispatch-empty">No history events match these filters.</p>}</div><footer className="dispatch-table-footer">Showing {events.length ? (page - 1) * 7 + 1 : 0}–{Math.min(page * 7, events.length)} of 184 events<div><button type="button" disabled={page <= 1} onClick={() => setPage((value) => value - 1)}>‹</button><button className="current" type="button">{page}</button><button type="button" disabled={events.length <= page * 7} onClick={() => setPage((value) => value + 1)}>{page + 1}</button><button type="button" disabled={events.length <= page * 7} onClick={() => setPage((value) => value + 1)}>›</button></div></footer></section>
  </div>;
}
