import { useState } from 'react';
import { AdminBadge, AdminHeader, AdminIcon, AdminPanel, AdminSelect, AdminStat } from '../components/AdminUI';

const risks = [
  ['30 Sep', 'Refrigerated capacity near limit', 'Kandy · Fresh', '15 of 16 vehicles needed', '91%'],
  ['1 Oct', 'Weekly fuel pressure', 'Peliyagoda', '3 vehicles near quota', '86%'],
  ['2 Oct', 'Small-van shortage', 'Both depots', '9 required · 8 available', '88%'],
  ['3 Oct', 'Late delivery probability', 'Kandy corridor', '18 min expected delay', '82%'],
];

export function ForecastPage() {
  const [range, setRange] = useState('Next 7 days');
  const [depot, setDepot] = useState('All depots');
  const [brand, setBrand] = useState('All brands');
  const [type, setType] = useState('All order types');
  return <div className="admin-page"><AdminHeader title="Forecast & Trends" subtitle="Future order demand, capacity pressure, and seasonal delivery risk." action={<button className="admin-button secondary" type="button" onClick={() => window.print()}><AdminIcon name="download"/>Export report</button>}/>
    <div className="admin-toolbar"><div className="admin-toolbar-filters"><AdminSelect value={depot} values={['All depots','Peliyagoda','Kandy']} onChange={setDepot}/><AdminSelect value={brand} values={['All brands','Fresh','Style','Tech']} onChange={setBrand}/><AdminSelect value={range} values={['Next 7 days','Next 14 days','Next 30 days']} onChange={setRange}/><AdminSelect value={type} values={['All order types','Dry','Chilled','Deferred']} onChange={setType}/></div><AdminBadge tone="neutral">Sample workspace</AdminBadge></div>
    <div className="admin-stats-grid four"><AdminStat label="Expected orders" value="1,385" note="↗ 18%　from comparable period" icon={<AdminIcon name="trend"/>} tone="green"/><AdminStat label="Peak demand day" value="02 Oct" note="Festival peak · 218 orders" icon={<AdminIcon name="calendar"/>} tone="purple"/><AdminStat label="Vehicles required" value="55/60" note="5 vehicles remain in network capacity" icon={<AdminIcon name="truck"/>} tone="purple"/><AdminStat label="Capacity pressure" value="15/16" note="Refrigerated required / available" icon={<AdminIcon name="alert"/>} tone="amber"/></div>
    <div className="admin-forecast-main"><AdminPanel title="Upcoming order trend" icon={<AdminIcon name="trend"/>} className="admin-forecast-chart-panel"><div className="admin-chart-legend"><span>● Actual</span><span>● Forecast</span><span>● Prediction range</span></div><div className="admin-line-chart tall"><div className="admin-chart-ylabels"><span>240</span><span>180</span><span>120</span><span>60</span><span>0</span></div><svg viewBox="0 0 700 260" preserveAspectRatio="none" role="img" aria-label="Upcoming order demand forecast"><path className="admin-chart-gridline" d="M0 24H700M0 78H700M0 132H700M0 186H700M0 240H700"/><path className="admin-chart-area" d="M350 94 C415 86 450 91 500 68 S565 42 600 54 S655 73 700 88 L700 111 C655 100 630 93 600 80 S550 78 500 91 S415 109 350 112Z"/><path className="admin-chart-line actual" d="M0 143 C90 131 160 122 235 112 S310 103 350 94"/><path className="admin-chart-line forecast" d="M350 94 C415 86 450 91 500 68 S565 42 600 54 S655 73 700 88"/></svg><div className="admin-chart-xlabels"><span>24</span><span>25</span><span>26</span><span>28</span><span>29</span><span>30</span><span>1</span><span>2</span><span>3</span><span>5</span></div></div><div className="admin-forecast-tags"><AdminBadge tone="blue">30 Sep · Payday</AdminBadge><AdminBadge tone="purple">2 Oct · Festival peak</AdminBadge><AdminBadge tone="amber">3 Oct · Monsoon</AdminBadge></div></AdminPanel>
      <AdminPanel title="Seasonal insight" icon={<AdminIcon name="calendar"/>} action={<AdminBadge tone="purple">Selected period</AdminBadge>} className="admin-seasonal-panel"><p>Calendar effects are compared with normal operating days for the same depot and brand.</p>{[['Fresh','Chilled and pre-8 AM demand','+21%','leaf'],['Style','Seasonal cartons and mall windows','+14%','shirt'],['Tech','Heavy, fragile order variability','+9%','monitor']].map(([label,desc,change,icon])=><div className="admin-seasonal-row" key={label}><i className={`brand-icon ${label.toLowerCase()}`}><AdminIcon name={icon as 'leaf'|'shirt'|'monitor'}/></i><div><strong>{label}</strong><small>{desc}</small><span className="admin-progress-track"><i style={{width:change}}/></span></div><AdminBadge tone="green">{change}</AdminBadge></div>)}<div className="admin-insight-note"><strong>◎ &nbsp; Strongest factor</strong><p>Festival build-up is adding 26% above a normal day.</p></div></AdminPanel>
    </div>
    <div className="admin-forecast-secondary"><AdminPanel title="Capacity forecast" icon={<AdminIcon name="truck"/>}>{[['All vehicles','55 / 60','Near capacity',92],['Refrigerated vehicles','15 / 16','Near capacity',94],['Small vans','9 / 8','Predicted shortage',100],['Weekly fuel','4,650 L / 4,400 L','Predicted shortage',100]].map(([label,value,note,percent])=><div className="admin-capacity-row" key={label as string}><div><strong>{label}</strong><b>{value}</b></div><i className={(note as string).includes('shortage')?'danger':''}><span style={{width:`${percent}%`}}/></i><small>{note}</small></div>)}</AdminPanel><AdminPanel title="Depot comparison" icon={<AdminIcon name="warehouse"/>}><div className="admin-chart-legend"><span>● Expected orders</span><span>● Vehicles needed</span><span>● Late-risk stops</span></div><div className="admin-compare-bars">{['Peliyagoda','Kandy'].map((name,index)=><div key={name}><i style={{height:index?'58%':'92%'}}/><i className="pale" style={{height:index?'18%':'25%'}}/><i className="amber" style={{height:index?'5%':'8%'}}/><span>{name}</span></div>)}</div></AdminPanel></div>
    <AdminPanel title="Upcoming risks" action={<span>Ranked by impact and confidence</span>}><div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>Date</th><th>Predicted risk</th><th>Affected area</th><th>Expected impact</th><th>Confidence</th></tr></thead><tbody>{risks.map((row) => <tr key={row[1]}><td><strong>{row[0]}</strong></td><td><strong>{row[1]}</strong><small>{row[1].slice(0,2).toUpperCase()}-0{risks.indexOf(row)+1}</small></td><td>{row[2]}</td><td>{row[3]}</td><td><AdminBadge tone={parseInt(row[4]) > 87 ? 'red' : 'amber'}>{row[4]}</AdminBadge></td></tr>)}</tbody></table></div></AdminPanel>
  </div>;
}
