import { useMemo, useState } from 'react';
import { AdminBadge, AdminDrawer, AdminHeader, AdminIcon, AdminPanel, AdminSearch, AdminSelect, AdminStat } from '../components/AdminUI';
import { adminFuelRecords } from '../data/adminData';

export function FuelIntegrityPage() {
  const [query,setQuery]=useState('');const [depot,setDepot]=useState('All depots');const [status,setStatus]=useState('All statuses');const [selected,setSelected]=useState<(typeof adminFuelRecords)[number]|null>(null);const [explained,setExplained]=useState<string[]>([]);
  const rows=useMemo(()=>adminFuelRecords.filter(r=>(!query||`${r.vehicle} ${r.driver} ${r.route} ${r.flag}`.toLowerCase().includes(query.toLowerCase()))&&(depot==='All depots'||r.depot===depot)&&(status==='All statuses'||(explained.includes(r.vehicle)?'Explained':r.status)===status)),[query,depot,status,explained]);
  return <div className="admin-page"><AdminHeader title="Fuel Integrity" subtitle="Review distance, fuel usage, and records that need attention." action={<button className="admin-button secondary" type="button" onClick={()=>window.print()}><AdminIcon name="download"/>Export report</button>}/><div className="admin-toolbar"><div className="admin-toolbar-filters"><AdminSelect value={depot} values={['All depots','Kandy','Peliyagoda']} onChange={setDepot}/><AdminSelect value={status} values={['All statuses','New','Reviewing','Explained']} onChange={setStatus}/></div><AdminBadge tone="neutral">Sample workspace</AdminBadge></div>
    <div className="admin-stats-grid four"><AdminStat label="Vehicles reviewed" value="04" note="Sample week · 28 Sep–03 Oct" icon={<AdminIcon name="truck"/>}/><AdminStat label="Open flags" value="03" note="Records that need checking" icon={<AdminIcon name="alert"/>} tone="amber"/><AdminStat label="Missing evidence" value="01" note="End odometer photo pending" icon={<AdminIcon name="file"/>}/><AdminStat label="Explained cases" value="01" note="Reviewed with supporting context" icon={<AdminIcon name="shield"/>} tone="green"/></div>
    <AdminPanel title="Flagged records" action={<AdminSearch value={query} onChange={setQuery}/>} className="admin-data-panel"><div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>Vehicle / driver</th><th>Depot</th><th>Flag</th><th>Planned / recorded</th><th>Status</th><th/></tr></thead><tbody>{rows.map((r)=>{const resolved=explained.includes(r.vehicle);return <tr key={r.vehicle} onClick={()=>setSelected(r)}><td><strong>{r.vehicle}</strong><small>{r.driver}</small></td><td><b>{r.depot}</b></td><td><strong>{r.flag}</strong><small>{r.route}</small></td><td><b>{r.distance}</b></td><td><AdminBadge tone={resolved||r.status==='Explained'?'green':r.status==='Reviewing'?'blue':'amber'}>{resolved?'Explained':r.status}</AdminBadge></td><td><button className="admin-text-link" type="button" onClick={(e)=>{e.stopPropagation();setSelected(r)}}>Review <AdminIcon name="chevron"/></button></td></tr>})}</tbody></table></div><footer className="admin-table-footer"><span>{rows.length} records</span><span>A flag is a request for review, not a finding of misconduct.</span></footer></AdminPanel>
    {selected&&<AdminDrawer title={selected.vehicle} subtitle="Fuel integrity record details" onClose={()=>setSelected(null)}><AdminBadge tone={explained.includes(selected.vehicle)?'green':selected.status==='Reviewing'?'blue':'amber'}>{explained.includes(selected.vehicle)?'Explained':selected.status}</AdminBadge><dl className="admin-detail-grid"><div><dt>Driver</dt><dd>{selected.driver}</dd></div><div><dt>Depot</dt><dd>{selected.depot}</dd></div><div><dt>Route</dt><dd>{selected.route}</dd></div><div><dt>Flag</dt><dd>{selected.flag}</dd></div><div><dt>Planned distance</dt><dd>{selected.distance.split(' / ')[0]} km</dd></div><div><dt>Recorded distance</dt><dd>{selected.distance.split(' / ')[1]}</dd></div></dl><section className="admin-drawer-section"><h3>Review context</h3><p className="admin-drawer-note">Compare the planned route, odometer records, and refuelling evidence before closing this flag.</p></section><button type="button" className="admin-button primary full" onClick={()=>setExplained((xs)=>xs.includes(selected.vehicle)?xs:[...xs,selected.vehicle])}>{explained.includes(selected.vehicle)?'Marked as explained':'Mark as explained'}</button></AdminDrawer>}
  </div>;
}
