/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as DriveRouteImport } from './routes/drive'
import { Route as LoadRouteImport } from './routes/load'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as StoreRouteImport } from './routes/store'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminConfigurationRouteImport } from './routes/admin.configuration'
import { Route as AdminFinesRouteImport } from './routes/admin.fines'
import { Route as AdminForecastRouteImport } from './routes/admin.forecast'
import { Route as AdminFuelRouteImport } from './routes/admin.fuel'
import { Route as AdminMasterDataRouteImport } from './routes/admin.master-data'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as DispatchIndexRouteImport } from './routes/dispatch.index'
import { Route as DispatchAlertsRouteImport } from './routes/dispatch.alerts'
import { Route as DispatchFleetRouteImport } from './routes/dispatch.fleet'
import { Route as DispatchHistoryRouteImport } from './routes/dispatch.history'
import { Route as DispatchLiveRouteImport } from './routes/dispatch.live'
import { Route as DispatchOrdersRouteImport } from './routes/dispatch.orders'
import { Route as DriveIndexRouteImport } from './routes/drive.index'
import { Route as DriveDeliveryRouteImport } from './routes/drive.delivery'
import { Route as DriveHistoryRouteImport } from './routes/drive.history'
import { Route as DriveProfileRouteImport } from './routes/drive.profile'
import { Route as LoadIndexRouteImport } from './routes/load.index'
import { Route as LoadDefectItemsRouteImport } from './routes/load.defect-items'
import { Route as LoadMissingItemsRouteImport } from './routes/load.missing-items'
import { Route as LoadScanPackagesRouteImport } from './routes/load.scan-packages'
import { Route as StoreIndexRouteImport } from './routes/store.index'
import { Route as StoreHistoryRouteImport } from './routes/store.history'
import { Route as StorePlaceOrderRouteImport } from './routes/store.place-order'
import { Route as StoreReceiveRouteImport } from './routes/store.receive'
import { Route as StoreTrackRouteImport } from './routes/store.track'
import { Route as DispatchPlanningIndexRouteImport } from './routes/dispatch.planning.index'
import { Route as DispatchPlanningProposalRouteImport } from './routes/dispatch.planning.proposal'
import { Route as DriveRouteIndexRouteImport } from './routes/drive.route.index'
import { Route as DriveRouteMapRouteImport } from './routes/drive.route.map'
import { Route as DispatchPlanningRoutesRouteIdRouteImport } from './routes/dispatch.planning.routes.$routeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const DriveRoute = DriveRouteImport.update({
  id: '/drive',
  path: '/drive',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadRoute = LoadRouteImport.update({
  id: '/load',
  path: '/load',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfigurationRoute = AdminConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinesRoute = AdminFinesRouteImport.update({
  id: '/fines',
  path: '/fines',
  getParentRoute: () => AdminRoute,
} as any)
const AdminForecastRoute = AdminForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFuelRoute = AdminFuelRouteImport.update({
  id: '/fuel',
  path: '/fuel',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMasterDataRoute = AdminMasterDataRouteImport.update({
  id: '/master-data',
  path: '/master-data',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const DispatchIndexRoute = DispatchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DispatchRoute,
} as any)
const DispatchAlertsRoute = DispatchAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => DispatchRoute,
} as any)
const DispatchFleetRoute = DispatchFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => DispatchRoute,
} as any)
const DispatchHistoryRoute = DispatchHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DispatchRoute,
} as any)
const DispatchLiveRoute = DispatchLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => DispatchRoute,
} as any)
const DispatchOrdersRoute = DispatchOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DispatchRoute,
} as any)
const DriveIndexRoute = DriveIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DriveRoute,
} as any)
const DriveDeliveryRoute = DriveDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => DriveRoute,
} as any)
const DriveHistoryRoute = DriveHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DriveRoute,
} as any)
const DriveProfileRoute = DriveProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DriveRoute,
} as any)
const LoadIndexRoute = LoadIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoadRoute,
} as any)
const LoadDefectItemsRoute = LoadDefectItemsRouteImport.update({
  id: '/defect-items',
  path: '/defect-items',
  getParentRoute: () => LoadRoute,
} as any)
const LoadMissingItemsRoute = LoadMissingItemsRouteImport.update({
  id: '/missing-items',
  path: '/missing-items',
  getParentRoute: () => LoadRoute,
} as any)
const LoadScanPackagesRoute = LoadScanPackagesRouteImport.update({
  id: '/scan-packages',
  path: '/scan-packages',
  getParentRoute: () => LoadRoute,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreRoute,
} as any)
const StoreHistoryRoute = StoreHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => StoreRoute,
} as any)
const StorePlaceOrderRoute = StorePlaceOrderRouteImport.update({
  id: '/place-order',
  path: '/place-order',
  getParentRoute: () => StoreRoute,
} as any)
const StoreReceiveRoute = StoreReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => StoreRoute,
} as any)
const StoreTrackRoute = StoreTrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => StoreRoute,
} as any)
const DispatchPlanningIndexRoute = DispatchPlanningIndexRouteImport.update({
  id: '/planning/',
  path: '/planning/',
  getParentRoute: () => DispatchRoute,
} as any)
const DispatchPlanningProposalRoute =
  DispatchPlanningProposalRouteImport.update({
    id: '/planning/proposal',
    path: '/planning/proposal',
    getParentRoute: () => DispatchRoute,
  } as any)
const DriveRouteIndexRoute = DriveRouteIndexRouteImport.update({
  id: '/route/',
  path: '/route/',
  getParentRoute: () => DriveRoute,
} as any)
const DriveRouteMapRoute = DriveRouteMapRouteImport.update({
  id: '/route/map',
  path: '/route/map',
  getParentRoute: () => DriveRoute,
} as any)
const DispatchPlanningRoutesRouteIdRoute =
  DispatchPlanningRoutesRouteIdRouteImport.update({
    id: '/planning/routes/$routeId',
    path: '/planning/routes/$routeId',
    getParentRoute: () => DispatchRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dispatch': typeof DispatchRouteWithChildren
  '/drive': typeof DriveRouteWithChildren
  '/load': typeof LoadRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/store': typeof StoreRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/configuration': typeof AdminConfigurationRoute
  '/admin/fines': typeof AdminFinesRoute
  '/admin/forecast': typeof AdminForecastRoute
  '/admin/fuel': typeof AdminFuelRoute
  '/admin/master-data': typeof AdminMasterDataRoute
  '/admin/users': typeof AdminUsersRoute
  '/dispatch/alerts': typeof DispatchAlertsRoute
  '/dispatch/fleet': typeof DispatchFleetRoute
  '/dispatch/history': typeof DispatchHistoryRoute
  '/dispatch/live': typeof DispatchLiveRoute
  '/dispatch/orders': typeof DispatchOrdersRoute
  '/drive/delivery': typeof DriveDeliveryRoute
  '/drive/history': typeof DriveHistoryRoute
  '/drive/profile': typeof DriveProfileRoute
  '/load/defect-items': typeof LoadDefectItemsRoute
  '/load/missing-items': typeof LoadMissingItemsRoute
  '/load/scan-packages': typeof LoadScanPackagesRoute
  '/store/history': typeof StoreHistoryRoute
  '/store/place-order': typeof StorePlaceOrderRoute
  '/store/receive': typeof StoreReceiveRoute
  '/store/track': typeof StoreTrackRoute
  '/admin/': typeof AdminIndexRoute
  '/dispatch/': typeof DispatchIndexRoute
  '/drive/': typeof DriveIndexRoute
  '/load/': typeof LoadIndexRoute
  '/store/': typeof StoreIndexRoute
  '/drive/route/map': typeof DriveRouteMapRoute
  '/dispatch/planning/proposal': typeof DispatchPlanningProposalRoute
  '/drive/route/': typeof DriveRouteIndexRoute
  '/dispatch/planning/': typeof DispatchPlanningIndexRoute
  '/dispatch/planning/routes/$routeId': typeof DispatchPlanningRoutesRouteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/configuration': typeof AdminConfigurationRoute
  '/admin/fines': typeof AdminFinesRoute
  '/admin/forecast': typeof AdminForecastRoute
  '/admin/fuel': typeof AdminFuelRoute
  '/admin/master-data': typeof AdminMasterDataRoute
  '/admin/users': typeof AdminUsersRoute
  '/dispatch/alerts': typeof DispatchAlertsRoute
  '/dispatch/fleet': typeof DispatchFleetRoute
  '/dispatch/history': typeof DispatchHistoryRoute
  '/dispatch/live': typeof DispatchLiveRoute
  '/dispatch/orders': typeof DispatchOrdersRoute
  '/drive/delivery': typeof DriveDeliveryRoute
  '/drive/history': typeof DriveHistoryRoute
  '/drive/profile': typeof DriveProfileRoute
  '/load/defect-items': typeof LoadDefectItemsRoute
  '/load/missing-items': typeof LoadMissingItemsRoute
  '/load/scan-packages': typeof LoadScanPackagesRoute
  '/store/history': typeof StoreHistoryRoute
  '/store/place-order': typeof StorePlaceOrderRoute
  '/store/receive': typeof StoreReceiveRoute
  '/store/track': typeof StoreTrackRoute
  '/admin': typeof AdminIndexRoute
  '/dispatch': typeof DispatchIndexRoute
  '/drive': typeof DriveIndexRoute
  '/load': typeof LoadIndexRoute
  '/store': typeof StoreIndexRoute
  '/drive/route/map': typeof DriveRouteMapRoute
  '/dispatch/planning/proposal': typeof DispatchPlanningProposalRoute
  '/drive/route': typeof DriveRouteIndexRoute
  '/dispatch/planning': typeof DispatchPlanningIndexRoute
  '/dispatch/planning/routes/$routeId': typeof DispatchPlanningRoutesRouteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dispatch': typeof DispatchRouteWithChildren
  '/drive': typeof DriveRouteWithChildren
  '/load': typeof LoadRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/store': typeof StoreRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/configuration': typeof AdminConfigurationRoute
  '/admin/fines': typeof AdminFinesRoute
  '/admin/forecast': typeof AdminForecastRoute
  '/admin/fuel': typeof AdminFuelRoute
  '/admin/master-data': typeof AdminMasterDataRoute
  '/admin/users': typeof AdminUsersRoute
  '/dispatch/alerts': typeof DispatchAlertsRoute
  '/dispatch/fleet': typeof DispatchFleetRoute
  '/dispatch/history': typeof DispatchHistoryRoute
  '/dispatch/live': typeof DispatchLiveRoute
  '/dispatch/orders': typeof DispatchOrdersRoute
  '/drive/delivery': typeof DriveDeliveryRoute
  '/drive/history': typeof DriveHistoryRoute
  '/drive/profile': typeof DriveProfileRoute
  '/load/defect-items': typeof LoadDefectItemsRoute
  '/load/missing-items': typeof LoadMissingItemsRoute
  '/load/scan-packages': typeof LoadScanPackagesRoute
  '/store/history': typeof StoreHistoryRoute
  '/store/place-order': typeof StorePlaceOrderRoute
  '/store/receive': typeof StoreReceiveRoute
  '/store/track': typeof StoreTrackRoute
  '/admin/': typeof AdminIndexRoute
  '/dispatch/': typeof DispatchIndexRoute
  '/drive/': typeof DriveIndexRoute
  '/load/': typeof LoadIndexRoute
  '/store/': typeof StoreIndexRoute
  '/drive/route/map': typeof DriveRouteMapRoute
  '/dispatch/planning/proposal': typeof DispatchPlanningProposalRoute
  '/drive/route/': typeof DriveRouteIndexRoute
  '/dispatch/planning/': typeof DispatchPlanningIndexRoute
  '/dispatch/planning/routes/$routeId': typeof DispatchPlanningRoutesRouteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dispatch'
    | '/drive'
    | '/load'
    | '/login'
    | '/setup'
    | '/store'
    | '/admin/audit'
    | '/admin/configuration'
    | '/admin/fines'
    | '/admin/forecast'
    | '/admin/fuel'
    | '/admin/master-data'
    | '/admin/users'
    | '/dispatch/alerts'
    | '/dispatch/fleet'
    | '/dispatch/history'
    | '/dispatch/live'
    | '/dispatch/orders'
    | '/drive/delivery'
    | '/drive/history'
    | '/drive/profile'
    | '/load/defect-items'
    | '/load/missing-items'
    | '/load/scan-packages'
    | '/store/history'
    | '/store/place-order'
    | '/store/receive'
    | '/store/track'
    | '/admin/'
    | '/dispatch/'
    | '/drive/'
    | '/load/'
    | '/store/'
    | '/drive/route/map'
    | '/dispatch/planning/proposal'
    | '/drive/route/'
    | '/dispatch/planning/'
    | '/dispatch/planning/routes/$routeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/setup'
    | '/admin/audit'
    | '/admin/configuration'
    | '/admin/fines'
    | '/admin/forecast'
    | '/admin/fuel'
    | '/admin/master-data'
    | '/admin/users'
    | '/dispatch/alerts'
    | '/dispatch/fleet'
    | '/dispatch/history'
    | '/dispatch/live'
    | '/dispatch/orders'
    | '/drive/delivery'
    | '/drive/history'
    | '/drive/profile'
    | '/load/defect-items'
    | '/load/missing-items'
    | '/load/scan-packages'
    | '/store/history'
    | '/store/place-order'
    | '/store/receive'
    | '/store/track'
    | '/admin'
    | '/dispatch'
    | '/drive'
    | '/load'
    | '/store'
    | '/drive/route/map'
    | '/dispatch/planning/proposal'
    | '/drive/route'
    | '/dispatch/planning'
    | '/dispatch/planning/routes/$routeId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dispatch'
    | '/drive'
    | '/load'
    | '/login'
    | '/setup'
    | '/store'
    | '/admin/audit'
    | '/admin/configuration'
    | '/admin/fines'
    | '/admin/forecast'
    | '/admin/fuel'
    | '/admin/master-data'
    | '/admin/users'
    | '/dispatch/alerts'
    | '/dispatch/fleet'
    | '/dispatch/history'
    | '/dispatch/live'
    | '/dispatch/orders'
    | '/drive/delivery'
    | '/drive/history'
    | '/drive/profile'
    | '/load/defect-items'
    | '/load/missing-items'
    | '/load/scan-packages'
    | '/store/history'
    | '/store/place-order'
    | '/store/receive'
    | '/store/track'
    | '/admin/'
    | '/dispatch/'
    | '/drive/'
    | '/load/'
    | '/store/'
    | '/drive/route/map'
    | '/dispatch/planning/proposal'
    | '/drive/route/'
    | '/dispatch/planning/'
    | '/dispatch/planning/routes/$routeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DispatchRoute: typeof DispatchRouteWithChildren
  DriveRoute: typeof DriveRouteWithChildren
  LoadRoute: typeof LoadRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  StoreRoute: typeof StoreRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drive': {
      id: '/drive'
      path: '/drive'
      fullPath: '/drive'
      preLoaderRoute: typeof DriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/load': {
      id: '/load'
      path: '/load'
      fullPath: '/load'
      preLoaderRoute: typeof LoadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuration': {
      id: '/admin/configuration'
      path: '/configuration'
      fullPath: '/admin/configuration'
      preLoaderRoute: typeof AdminConfigurationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fines': {
      id: '/admin/fines'
      path: '/fines'
      fullPath: '/admin/fines'
      preLoaderRoute: typeof AdminFinesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/forecast': {
      id: '/admin/forecast'
      path: '/forecast'
      fullPath: '/admin/forecast'
      preLoaderRoute: typeof AdminForecastRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fuel': {
      id: '/admin/fuel'
      path: '/fuel'
      fullPath: '/admin/fuel'
      preLoaderRoute: typeof AdminFuelRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/master-data': {
      id: '/admin/master-data'
      path: '/master-data'
      fullPath: '/admin/master-data'
      preLoaderRoute: typeof AdminMasterDataRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dispatch/': {
      id: '/dispatch/'
      path: '/'
      fullPath: '/dispatch/'
      preLoaderRoute: typeof DispatchIndexRouteImport
      parentRoute: typeof DispatchRoute
    }
    '/dispatch/alerts': {
      id: '/dispatch/alerts'
      path: '/alerts'
      fullPath: '/dispatch/alerts'
      preLoaderRoute: typeof DispatchAlertsRouteImport
      parentRoute: typeof DispatchRoute
    }
    '/dispatch/fleet': {
      id: '/dispatch/fleet'
      path: '/fleet'
      fullPath: '/dispatch/fleet'
      preLoaderRoute: typeof DispatchFleetRouteImport
      parentRoute: typeof DispatchRoute
    }
    '/dispatch/history': {
      id: '/dispatch/history'
      path: '/history'
      fullPath: '/dispatch/history'
      preLoaderRoute: typeof DispatchHistoryRouteImport
      parentRoute: typeof DispatchRoute
    }
    '/dispatch/live': {
      id: '/dispatch/live'
      path: '/live'
      fullPath: '/dispatch/live'
      preLoaderRoute: typeof DispatchLiveRouteImport
      parentRoute: typeof DispatchRoute
    }
    '/dispatch/orders': {
      id: '/dispatch/orders'
      path: '/orders'
      fullPath: '/dispatch/orders'
      preLoaderRoute: typeof DispatchOrdersRouteImport
      parentRoute: typeof DispatchRoute
    }
    '/drive/': {
      id: '/drive/'
      path: '/'
      fullPath: '/drive/'
      preLoaderRoute: typeof DriveIndexRouteImport
      parentRoute: typeof DriveRoute
    }
    '/drive/delivery': {
      id: '/drive/delivery'
      path: '/delivery'
      fullPath: '/drive/delivery'
      preLoaderRoute: typeof DriveDeliveryRouteImport
      parentRoute: typeof DriveRoute
    }
    '/drive/history': {
      id: '/drive/history'
      path: '/history'
      fullPath: '/drive/history'
      preLoaderRoute: typeof DriveHistoryRouteImport
      parentRoute: typeof DriveRoute
    }
    '/drive/profile': {
      id: '/drive/profile'
      path: '/profile'
      fullPath: '/drive/profile'
      preLoaderRoute: typeof DriveProfileRouteImport
      parentRoute: typeof DriveRoute
    }
    '/load/': {
      id: '/load/'
      path: '/'
      fullPath: '/load/'
      preLoaderRoute: typeof LoadIndexRouteImport
      parentRoute: typeof LoadRoute
    }
    '/load/defect-items': {
      id: '/load/defect-items'
      path: '/defect-items'
      fullPath: '/load/defect-items'
      preLoaderRoute: typeof LoadDefectItemsRouteImport
      parentRoute: typeof LoadRoute
    }
    '/load/missing-items': {
      id: '/load/missing-items'
      path: '/missing-items'
      fullPath: '/load/missing-items'
      preLoaderRoute: typeof LoadMissingItemsRouteImport
      parentRoute: typeof LoadRoute
    }
    '/load/scan-packages': {
      id: '/load/scan-packages'
      path: '/scan-packages'
      fullPath: '/load/scan-packages'
      preLoaderRoute: typeof LoadScanPackagesRouteImport
      parentRoute: typeof LoadRoute
    }
    '/store/': {
      id: '/store/'
      path: '/'
      fullPath: '/store/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/history': {
      id: '/store/history'
      path: '/history'
      fullPath: '/store/history'
      preLoaderRoute: typeof StoreHistoryRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/place-order': {
      id: '/store/place-order'
      path: '/place-order'
      fullPath: '/store/place-order'
      preLoaderRoute: typeof StorePlaceOrderRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/receive': {
      id: '/store/receive'
      path: '/receive'
      fullPath: '/store/receive'
      preLoaderRoute: typeof StoreReceiveRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/track': {
      id: '/store/track'
      path: '/track'
      fullPath: '/store/track'
      preLoaderRoute: typeof StoreTrackRouteImport
      parentRoute: typeof StoreRoute
    }
    '/dispatch/planning/': {
      id: '/dispatch/planning/'
      path: '/planning'
      fullPath: '/dispatch/planning/'
      preLoaderRoute: typeof DispatchPlanningIndexRouteImport
      parentRoute: typeof DispatchRoute
    }
    '/dispatch/planning/proposal': {
      id: '/dispatch/planning/proposal'
      path: '/planning/proposal'
      fullPath: '/dispatch/planning/proposal'
      preLoaderRoute: typeof DispatchPlanningProposalRouteImport
      parentRoute: typeof DispatchRoute
    }
    '/drive/route/': {
      id: '/drive/route/'
      path: '/route'
      fullPath: '/drive/route/'
      preLoaderRoute: typeof DriveRouteIndexRouteImport
      parentRoute: typeof DriveRoute
    }
    '/drive/route/map': {
      id: '/drive/route/map'
      path: '/route/map'
      fullPath: '/drive/route/map'
      preLoaderRoute: typeof DriveRouteMapRouteImport
      parentRoute: typeof DriveRoute
    }
    '/dispatch/planning/routes/$routeId': {
      id: '/dispatch/planning/routes/$routeId'
      path: '/planning/routes/$routeId'
      fullPath: '/dispatch/planning/routes/$routeId'
      preLoaderRoute: typeof DispatchPlanningRoutesRouteIdRouteImport
      parentRoute: typeof DispatchRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminConfigurationRoute: typeof AdminConfigurationRoute
  AdminFinesRoute: typeof AdminFinesRoute
  AdminForecastRoute: typeof AdminForecastRoute
  AdminFuelRoute: typeof AdminFuelRoute
  AdminMasterDataRoute: typeof AdminMasterDataRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminConfigurationRoute: AdminConfigurationRoute,
  AdminFinesRoute: AdminFinesRoute,
  AdminForecastRoute: AdminForecastRoute,
  AdminFuelRoute: AdminFuelRoute,
  AdminMasterDataRoute: AdminMasterDataRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DispatchRouteChildren {
  DispatchAlertsRoute: typeof DispatchAlertsRoute
  DispatchFleetRoute: typeof DispatchFleetRoute
  DispatchHistoryRoute: typeof DispatchHistoryRoute
  DispatchLiveRoute: typeof DispatchLiveRoute
  DispatchOrdersRoute: typeof DispatchOrdersRoute
  DispatchIndexRoute: typeof DispatchIndexRoute
  DispatchPlanningProposalRoute: typeof DispatchPlanningProposalRoute
  DispatchPlanningIndexRoute: typeof DispatchPlanningIndexRoute
  DispatchPlanningRoutesRouteIdRoute: typeof DispatchPlanningRoutesRouteIdRoute
}

const DispatchRouteChildren: DispatchRouteChildren = {
  DispatchAlertsRoute: DispatchAlertsRoute,
  DispatchFleetRoute: DispatchFleetRoute,
  DispatchHistoryRoute: DispatchHistoryRoute,
  DispatchLiveRoute: DispatchLiveRoute,
  DispatchOrdersRoute: DispatchOrdersRoute,
  DispatchIndexRoute: DispatchIndexRoute,
  DispatchPlanningProposalRoute: DispatchPlanningProposalRoute,
  DispatchPlanningIndexRoute: DispatchPlanningIndexRoute,
  DispatchPlanningRoutesRouteIdRoute: DispatchPlanningRoutesRouteIdRoute,
}

const DispatchRouteWithChildren = DispatchRoute._addFileChildren(
  DispatchRouteChildren,
)

interface DriveRouteChildren {
  DriveDeliveryRoute: typeof DriveDeliveryRoute
  DriveHistoryRoute: typeof DriveHistoryRoute
  DriveProfileRoute: typeof DriveProfileRoute
  DriveIndexRoute: typeof DriveIndexRoute
  DriveRouteMapRoute: typeof DriveRouteMapRoute
  DriveRouteIndexRoute: typeof DriveRouteIndexRoute
}

const DriveRouteChildren: DriveRouteChildren = {
  DriveDeliveryRoute: DriveDeliveryRoute,
  DriveHistoryRoute: DriveHistoryRoute,
  DriveProfileRoute: DriveProfileRoute,
  DriveIndexRoute: DriveIndexRoute,
  DriveRouteMapRoute: DriveRouteMapRoute,
  DriveRouteIndexRoute: DriveRouteIndexRoute,
}

const DriveRouteWithChildren = DriveRoute._addFileChildren(DriveRouteChildren)

interface LoadRouteChildren {
  LoadDefectItemsRoute: typeof LoadDefectItemsRoute
  LoadMissingItemsRoute: typeof LoadMissingItemsRoute
  LoadScanPackagesRoute: typeof LoadScanPackagesRoute
  LoadIndexRoute: typeof LoadIndexRoute
}

const LoadRouteChildren: LoadRouteChildren = {
  LoadDefectItemsRoute: LoadDefectItemsRoute,
  LoadMissingItemsRoute: LoadMissingItemsRoute,
  LoadScanPackagesRoute: LoadScanPackagesRoute,
  LoadIndexRoute: LoadIndexRoute,
}

const LoadRouteWithChildren = LoadRoute._addFileChildren(LoadRouteChildren)

interface StoreRouteChildren {
  StoreHistoryRoute: typeof StoreHistoryRoute
  StorePlaceOrderRoute: typeof StorePlaceOrderRoute
  StoreReceiveRoute: typeof StoreReceiveRoute
  StoreTrackRoute: typeof StoreTrackRoute
  StoreIndexRoute: typeof StoreIndexRoute
}

const StoreRouteChildren: StoreRouteChildren = {
  StoreHistoryRoute: StoreHistoryRoute,
  StorePlaceOrderRoute: StorePlaceOrderRoute,
  StoreReceiveRoute: StoreReceiveRoute,
  StoreTrackRoute: StoreTrackRoute,
  StoreIndexRoute: StoreIndexRoute,
}

const StoreRouteWithChildren = StoreRoute._addFileChildren(StoreRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DispatchRoute: DispatchRouteWithChildren,
  DriveRoute: DriveRouteWithChildren,
  LoadRoute: LoadRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  StoreRoute: StoreRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
