import { useMemo, useState } from 'react';
import { useOutletContext } from 'react-router-dom';
import { DispatchIcon, DispatcherBadge, DispatcherPageHeader, DispatcherStat } from '../components/DispatcherUI';
import { incidents } from '../data/dispatcherData';

export function EmergencyPage() {
  const { searchQuery = '' } = useOutletContext<{ searchQuery?: string }>();
  const [search, setSearch] = useState('');
  const [priority, setPriority] = useState('All priorities');
  const [statusFilter, setStatusFilter] = useState('All statuses');
  const [sort, setSort] = useState('Newest');
  const [resolved, setResolved] = useState<string[]>([]);
  const [message, setMessage] = useState('');
  const query = `${searchQuery} ${search}`.trim().toLowerCase();
  const rows = useMemo(() => incidents.filter((item) => (!query || `${item.id} ${item.title} ${item.driver} ${item.vehicle} ${item.route} ${item.location}`.toLowerCase().includes(query)) && (priority === 'All priorities' || item.priority === priority.toLowerCase()) && (statusFilter === 'All statuses' || (statusFilter === 'Resolved' ? resolved.includes(item.id) : !resolved.includes(item.id)))), [query, priority, statusFilter, resolved]);
  const resolveIncident = (id: string) => { setResolved((current) => current.includes(id) ? current : [...current, id]); setMessage(`${id} marked as resolved.`); };
  return <div className="dispatch-page dispatch-emergency-page"><DispatcherPageHeader title="Emergency" subtitle="Active driver and vehicle incidents requiring dispatcher attention." action={<span className="dispatch-coverage"><i />Dispatch coverage online</span>} />
    {message && <div className="dispatch-success-notice" role="status">{message}<button type="button" onClick={() => setMessage('')} aria-label="Dismiss">×</button></div>}
    <section className="dispatch-emergency-stats"><DispatcherStat label="Active emergencies" value={String(incidents.length - resolved.length)} note="1 critical" icon={<DispatchIcon name="alert" />} /><DispatcherStat label="Awaiting support" value="1" note="18 km away" icon={<DispatchIcon name="pin" />} /><DispatcherStat label="Avg. response" value="11m" note="within target" icon={<DispatchIcon name="clock" />} /><DispatcherStat label="Resolved today" value={String(6 + resolved.length)} note="last at 10:04" icon={<DispatchIcon name="check" />} /></section>
    <div className="dispatch-emergency-controls"><label className="dispatch-emergency-search"><span>⌕</span><input type="search" placeholder="Search driver, vehicle, incident ID, or location" value={search} onChange={(event) => setSearch(event.target.value)} /></label><select aria-label="Filter by priority" value={priority} onChange={(event) => setPriority(event.target.value)}>{['All priorities', 'Critical', 'High', 'Elevated'].map((value) => <option key={value}>{value}</option>)}</select><select aria-label="Filter by status" value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)}>{['All statuses', 'Active', 'Resolved'].map((value) => <option key={value}>{value}</option>)}</select><select aria-label="Sort incidents" value={sort} onChange={(event) => setSort(event.target.value)}><option>Newest</option><option>Oldest</option></select></div>
    <div className="dispatch-section-heading"><h2>Active incidents</h2><span>Live updates · refreshed just now</span></div>
    <section className="dispatch-incident-list">{(sort === 'Newest' ? rows : [...rows].reverse()).map((incident) => { const isResolved = resolved.includes(incident.id); return <article className={`dispatch-incident-card ${incident.priority}`} key={incident.id}><div className="dispatch-incident-primary"><div className="dispatch-incident-kicker"><DispatcherBadge tone={incident.priority}>{incident.priority}</DispatcherBadge><span>{incident.id}</span></div><h3>{incident.title}</h3><p>{incident.description}</p></div><div className="dispatch-incident-facts"><div><span>Driver</span><strong>{incident.driver}</strong></div><div><span>Route</span><strong>{incident.route}</strong></div><div><span>Vehicle</span><strong>{incident.vehicle}</strong></div><div><span>Last location</span><strong><DispatchIcon name="pin" />{incident.location}</strong></div></div><div className="dispatch-incident-actions"><time>{incident.time}</time><strong className={isResolved ? 'resolved' : ''}>{isResolved ? 'Resolved' : incident.status}</strong><small>{incident.meta}</small><div><button className="dispatch-outline-button" type="button" onClick={() => setMessage(`${incident.id}: ${incident.title} · ${incident.description}`)}>↗ View details</button><button className="dispatch-primary-button" type="button" onClick={() => setMessage(`Contact request prepared for ${incident.driver}.`)}>☎ Contact driver</button></div><div><button className="dispatch-outline-button" type="button" onClick={() => setMessage(`Support assignment opened for ${incident.id}.`)}>♙ Assign support</button>{incident.priority === 'critical' ? <button className="dispatch-danger-button" type="button" onClick={() => setMessage(`${incident.id} escalated to emergency response.`)}>⚠ Escalate</button> : <button className="dispatch-text-button" type="button" onClick={() => resolveIncident(incident.id)}>✓ Resolve</button>}</div></div></article>; })}{rows.length === 0 && <p className="dispatch-empty">No incidents match these filters.</p>}</section>
  </div>;
}
