import { useMemo, useState } from 'react';
import { DispatchIcon, DispatcherBadge, DispatcherPageHeader, DispatcherStat } from '../components/DispatcherUI';
import { fleetVehicles } from '../data/dispatcherData';

export function FleetFuelPage() {
  const [lowFuelOnly, setLowFuelOnly] = useState(false);
  const [depot, setDepot] = useState('All depots');
  const vehicles = useMemo(() => fleetVehicles.filter((vehicle) => (!lowFuelOnly || vehicle.fuel / vehicle.quota <= .5) && (depot === 'All depots' || vehicle.depot === depot)), [lowFuelOnly, depot]);
  const activeVehicles = 75;
  const lowFuel = 3;
  return <div className="dispatch-page dispatch-fleet-page"><DispatcherPageHeader title="Fleet & Fuel" />
    <div className="dispatch-fleet-stats"><div role="button" tabIndex={0} className="dispatch-fleet-stat-button" onClick={() => setLowFuelOnly(false)} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') setLowFuelOnly(false); }}><DispatcherStat label="Active Vehicles" value={String(activeVehicles)} icon={<span className="dispatch-mini-bars" aria-label="Fleet activity chart"><span /><span /><span /><span /><span /></span>} /></div><div role="button" tabIndex={0} className={`dispatch-fleet-stat-button${lowFuelOnly ? ' active' : ''}`} onClick={() => setLowFuelOnly((value) => !value)} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') setLowFuelOnly((value) => !value); }}><DispatcherStat label="Low fuel Vehicles" value={String(lowFuel)} icon={<DispatchIcon name="fuel" />} /></div><article className="dispatch-quota-card"><span>Total fuel quota</span><strong>50% <small>left</small></strong><b>12,400 L available</b></article></div>
    <section className="dispatch-fleet-table-card"><header><strong>Fleet</strong><label>Depot<select value={depot} onChange={(event) => setDepot(event.target.value)}><option>All depots</option><option>Peliyagoda</option><option>Kandy</option></select></label></header><div className="dispatch-table-scroll"><table className="dispatch-fleet-table"><thead><tr><th>Vehicle</th><th>Type / temp</th><th>Capacity</th><th>Depot</th><th>Trips</th><th>Weekly fuel quota</th><th>Status</th></tr></thead><tbody>{vehicles.map((vehicle) => { const remaining = Math.round(vehicle.fuel / vehicle.quota * 100); return <tr key={vehicle.code}><td><strong>{vehicle.id}</strong><small>{vehicle.code}</small></td><td>{vehicle.type} · <DispatcherBadge tone={vehicle.temperature}>{vehicle.temperature}</DispatcherBadge></td><td>{vehicle.capacity}</td><td>{vehicle.depot}</td><td>{vehicle.trips}</td><td><div className={`dispatch-fuel-value${remaining < 30 ? ' low' : ''}`}><span>{vehicle.fuel} L of {vehicle.quota} L left</span><b>{remaining}%</b></div><span className="dispatch-fuel-track"><i style={{ width: `${remaining}%` }} /></span></td><td><DispatcherBadge tone={vehicle.status}>{vehicle.status}</DispatcherBadge></td></tr>; })}</tbody></table>{vehicles.length === 0 && <p className="dispatch-empty">No fleet vehicles match this filter.</p>}</div></section>
  </div>;
}
